spring:
  application:
    name: shopping
  datasource:
    url: ${DBURL:jdbc:mysql://localhost:3306/testdb}
    username: root
    password: ${PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Seoul
    show_sql: true
  data:
    redis:
      host: ${redis.host:localhost}
      port: ${redis.host:6379}
# 해당 환경변수는 비밀번호이므로 yml에 저장하면 안되고
# 따로 Edit Configuration - Environment Variable에서 PASSWORD:1234로 지정
PASSWORD: 1234
jwt:
  keyId: ${ketId:TopOfTheHeadKey}
  accessTokenExpiration: ${accssTokenMinute:5}
  refreshTokenExpiration: ${refreshTokenMinute:720}

server:
  port: 8083

